---
- name: create wg client config from template
  template:
    dest: "/etc/wireguard/{{wg_interface_name}}.conf"
    src: templates/client.conf.j2
    owner: root
    group: root
    mode: '0600'
  notify: restart wg service
