---
- name: create wg server config from template
  template:
    dest: "/etc/wireguard/{{wg_interface_name}}.conf"
    src: templates/server.conf.j2
    owner: root
    group: root
    mode: '0600'
  notify: restart wg service


- name: enable ipv4 and v6 forwarding
  sysctl:
    name: "{{item}}"
    value: "1"
    sysctl_set: yes
    reload: yes
  with_items:
    - "net.ipv4.ip_forward"
    - "net.ipv6.conf.all.forwarding"
